server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: lb://APIGATEWAY
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<segment>.*), /${segment}/v3/api-docs
        - id : USER-SERVICE
          uri : lb://USERSERVICE
          predicates:
            - Path=/users/**,/user-service/api-docs
        - id: HOTEL-SERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**, /hotel-service/api-docs
        - id: RATING-SERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**, /rating-service/api-docs
    discovery:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
      - url: /user-service/api-docs
        name: User Service
      - url: /rating-service/api-docs
        name: Rating Service
      - url: /hotel-service/api-docs
        name: Hotel Service
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


