server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name:  AUTH-SERVICE

  config:
    import: optional:configserver:http://localhost:8085


# Swagger Documentation
openapi:
  service:
    title: Auth Service Documentation
    version: 3.0.1
    url: lb://APIGATEWAY #api gateway url
springdoc:
  swagger-ui:
    path: /auth-service/swagger-ui.html
  api-docs:
    path: /auth-service/api-docs
