spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rashidmakki/microservice-tutorial-config
          clone-on-start: true
server:
  port: 8085